# Generated by Django 4.2.2 on 2023-06-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedServ_app', '0003_alter_productomedico_p_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomedico',
            name='p_precio',
            field=models.IntegerField(),
        ),
    ]
