# Generated by Django 4.2.2 on 2023-06-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedServ_app', '0004_alter_productomedico_p_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomedico',
            name='p_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
