# Generated by Django 4.2.2 on 2023-06-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedServ_app', '0005_productomedico_p_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomedico',
            name='p_numb',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
