# Generated by Django 4.2.2 on 2023-07-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedServ_app', '0006_productomedico_p_numb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Sugerencia'], [2, 'Reclamo'], [3, 'No deseo Responder'], [4, 'Otro']])),
                ('mensajes', models.TextField(max_length=500)),
                ('aviso', models.BooleanField(verbose_name='Acepto Términos y Condiciones')),
                ('fecha_enviado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
